/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication(scanBasePackages = "org.example") // , exclude =
                                                         // {
                                                         // DataSourceAutoConfiguration.class
                                                         // }
@EnableJpaRepositories(basePackages = "org.example.repository")
public class App {

    String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
        // println new App().greeting
    }
}
